{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-zip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/zip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/zip/zip_{{ version }}.tar.gz
  sha256: 5f92c09979bc278c94c8ee53bc6c2a5443227ffdb10ad8db6d015e2a57327e7f

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-cli
  run:
    - r-base
    - r-cli

test:
  commands:
    - $R -e "library('zip')"           # [not win]
    - "\"%R%\" -e \"library('zip')\""  # [win]

about:
  home: https://r-lib.github.io/zip/
  dev_url: https://github.com/r-lib/zip
  license: MIT
  summary: Cross-Platform 'zip' Compression Library. A replacement for the 'zip' function, that does not require any additional external tools on any platform.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
