# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Un658QhFSPRlbQwGbToZkwZcYST1+dVmdnEDYU5OlFTqhnMaO/VnTobKCB0Fu0kTCGqy3s77K/2MLCd9MNto16XvBFRkqh16nqClui/QaJPDFkiWrerERT3vO2q5R8ZQm/EbdGHFhhcm7H49I4gEME8vA/XMBONqeZi8Sp5YtM2e8wafqOyAWhMlH8EQOnYimpH+0WEU9Lr40hnCilbdatXfRbuMbQq8bzKNKHY9HJ6GNRNBBD8zV53m/Ws/dVzs2L5TgkOXaDRDU8San+tiTTo3IpS+8mMnqWCJqW0r8d2p8ssaEXlNg+SXSS+l92suocnIIOCII5IgL30+7b8SFlvIchlhspMe0XVArdrc+KV7rMC8ZGnNou/YAmQt5b9c7ArRMyla8HSxz/DqxPMcrrLRkUnkVsl+JVwADgXX1T7xNCppQsIGvGcU4nVD3A7d4mFtIHybrrrPzIj6fgM6ReteLXjz6q24CJrDghVGA7tOA0QAfXflKuZWCqow6CRqVJ8iabUNbiX03MkpulfwWVmgzbNVGq8BZkX8J31Uc++C5mRo+5sOkhOH09ZjhSZ7RsyxV1UiriGaT+ZC5UsoHuNRGObhDr9V09C6scN2Fj1nqtvd0UUDDetfOxDK/r+F5DiHdYKMyqqaAQyu77GLUNRjHVa8V7R3NIqjElSux94="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
