appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Un658QhFSPRlbQwGbToZkwZcYST1+dVmdnEDYU5OlFTqhnMaO/VnTobKCB0Fu0kTCGqy3s77K/2MLCd9MNto16XvBFRkqh16nqClui/QaJPDFkiWrerERT3vO2q5R8ZQm/EbdGHFhhcm7H49I4gEME8vA/XMBONqeZi8Sp5YtM2e8wafqOyAWhMlH8EQOnYimpH+0WEU9Lr40hnCilbdatXfRbuMbQq8bzKNKHY9HJ6GNRNBBD8zV53m/Ws/dVzs2L5TgkOXaDRDU8San+tiTTo3IpS+8mMnqWCJqW0r8d2p8ssaEXlNg+SXSS+l92suocnIIOCII5IgL30+7b8SFlvIchlhspMe0XVArdrc+KV7rMC8ZGnNou/YAmQt5b9c7ArRMyla8HSxz/DqxPMcrrLRkUnkVsl+JVwADgXX1T7xNCppQsIGvGcU4nVD3A7d4mFtIHybrrrPzIj6fgM6ReteLXjz6q24CJrDghVGA7tOA0QAfXflKuZWCqow6CRqVJ8iabUNbiX03MkpulfwWVmgzbNVGq8BZkX8J31Uc++C5mRo+5sOkhOH09ZjhSZ7RsyxV1UiriGaT+ZC5UsoHuNRGObhDr9V09C6scN2Fj1nqtvd0UUDDetfOxDK/r+F5DiHdYKMyqqaAQyu77GLUNRjHVa8V7R3NIqjElSux94=
conda_forge_output_validation: true
